{% set name = "opentelemetry-instrumentation-pymongo" %}
{% set version = "0.41b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pymongo-{{ version }}.tar.gz
  sha256: 050a8cf53bda21a51ee4cc45a045e3e16cec7f07e10f7a451d68c8202760977a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.41b0
    - opentelemetry-semantic-conventions ==0.41b0
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pymongo 
    # - pymongo <5.0,>=3.1
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pymongo 
test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pymongo
  summary: OpenTelemetry pymongo instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
